### ISSUE TITLE
【Poseidon v1】error for chat lib

### ISSUE THREAD

**Issue by yingjingyang** [Poseidon-ZKP/zkShuffle#70]
![截屏2023-06-09 上午11.36.18.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/1c9c4595-d8ad-4617-9002-fec379343c0f)

**Comment by Haily5** [comment]
If not operated for a long time， chat will be disconnect.  It can reconnect to server,  and we also remove panel in the release  version
